name: My first example

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4  
    
    - name: Welcome message
      run: | 
        echo "My first github action job"
        ls -la
        cat README.md   
        ls -la ..