name: Generate ASCII Artwork dragon

on:
  push

jobs:
  ascii_list_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Cowsay program, create and open dragon.txt
        run: |
          ls -la
          chmod +x ascii-script.sh
          

  ascii_job_run_script:
    needs: ascii_list_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Cowsay program, create and open dragon.txt
        run: |
          ./ascii-script.sh
          

   ascii__list_job:
    needs: ascii_list_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Cowsay program, create and open dragon.txt
        run: |
          ls -la
