name: Generate ASCII Artwork dragon

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Cowsay program, create and open dragon.txt
        run: ./ascii-script.sh

