name: Generate ASCII Artwork dragon

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Cowsay program
        uses: sudo apt-get install cowsay -y

      - name: Run Cowsay CMD
        uses: cowsay -f dragon "Run for cover, I am a Dragon RAWR ! ! !" >> dragon.txt

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

      - name: Read dragon.txt
        run: cat dragon.txt

      - name: Checkout Repo Files
        run: ls -la
